platform :ios, '16.0'

flutter_application_path = '../confirm_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'LegacyApp' do
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer)
end
